# Generated by Django 4.1.7 on 2023-02-25 23:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DancingDate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=50)),
                ('ddate', models.DateField()),
                ('ntime', models.IntegerField()),
                ('scontact', models.CharField(max_length=50)),
            ],
        ),
    ]
